spring.application.name=SimleaBackendTest

linkedin.client-id=${LINKEDIN_CLIENT_ID}
linkedin.client-secret=${LINKEDIN_CLIENT_CRED}
linkedin.redirect-uri=http://localhost:4200/auth/callback
linkedin.scope=openid profile email

server.port=8080
